### ISSUE TITLE
SipPhone.register fails with ParseException when server responds with TO header without tag part

### ISSUE THREAD

**Issue by kkorsakov** [RestComm/sipunit#3]
Exception is

```
failed to register Exception while cloning request: java.text.ParseException: null or empty token
java.text.ParseException: null or empty token
        at gov.nist.javax.sip.parser.Parser.checkToken(Parser.java:115)
        at gov.nist.javax.sip.header.To.setTag(To.java:175)
        at org.cafesip.sipunit.SipPhone.processAuthChallenge(SipPhone.java:701)
        at org.cafesip.sipunit.SipPhone.sendRegistrationMessage(SipPhone.java:563)
        at org.cafesip.sipunit.SipPhone.register(SipPhone.java:353)
        at org.cafesip.sipunit.SipPhone.register(SipPhone.java:231)
```

Response

```
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP X.X.X.X:5090;branch=z9hG4bK-373233-244216aa01ac5c3bbc3aadcc5c91e47e;received=X.X.X.X
From: <sip:1001@X.X.X.X.>;tag=482602994
To: <sip:1001@X.X.X.X>
Call-ID: 7472556513545112754@X.X.X.X.
CSeq: 1 REGISTER
WWW-Authenticate: Digest realm="X.X.X.X.", nonce="a2a9903d542bedb1618d948f477bb2be.1436996491", stale=FALSE, algorithm=MD5
Server: V4 0.1.1-48
Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO
Content-Length: 0
```

I'm not sure is tag is mandatory for To in this response, but i think it won't be bad to check for tag existence before trying to set it in SipPhone:701

**Comment by deruelle** [comment]
I do think the To Tag is mandatory as per RFC 3261 for any non provisional response. 
I think this issue should be fixed now as Issue #2 was fixed yesterday which was setting the ToTag on the challenge request. Now that this code is gone, this exception shouldn't pop up anymore. Can you confirm against 2.0.1 https://oss.sonatype.org/content/repositories/releases/org/mobicents/sipunit/sipunit/2.0.1/ ?

Thanks
